/**
 * Google Sign-In client IDs.
 *
 * Both are **public identifiers, not credentials**. They are compiled into every
 * copy of the app and can be read out of any installed build, which is why they
 * live in the repository rather than in a secret — unlike YELP_API_KEY or
 * ANTHROPIC_API_KEY, there is nothing here for anyone to steal. Google's own
 * setup instructions have you commit them. The client *secret* is the sensitive
 * half of an OAuth pair, and mobile apps do not have one.
 *
 * Two IDs, and both are needed for different reasons:
 *
 *  - `IOS_CLIENT_ID` identifies this app to Google. It matches CLIENT_ID in
 *    ios/CigarLoungeApp/GoogleService-Info.plist, and its reversed form is
 *    declared as a URL scheme in Info.plist so Google's browser hand-off can get
 *    back into the app.
 *  - `WEB_CLIENT_ID` is what makes the sign-in usable by Firebase. Google issues
 *    the ID token with this as its audience, and Firebase will only accept a
 *    token whose audience is the project's web client. Omit it and sign-in
 *    appears to work right up until Firebase rejects the credential.
 *
 * Generated by Firebase when Google sign-in was enabled on 2026-08-19. Both come
 * from console.cloud.google.com → APIs & Services → Credentials; the web one is
 * listed as "Web client (auto created by Google Service)".
 */

export const IOS_CLIENT_ID =
  '345721268939-8hhh4gau0ditkr9anv2hqq0clpd43fnn.apps.googleusercontent.com';

export const WEB_CLIENT_ID =
  '345721268939-p3h07g32n86v9g9hi23jl6q8gmet6m8b.apps.googleusercontent.com';

/**
 * Whether the IDs look like real Google client IDs rather than placeholders.
 *
 * The app has a standing pattern of shipping features against placeholder
 * credentials and switching them on later (YELP_API_KEY, GOOGLE_PLACES_API_KEY,
 * ANTHROPIC_API_KEY). This lets the Google button hide itself rather than offer a
 * sign-in that cannot possibly complete.
 */
export function isGoogleSignInConfigured(): boolean {
  return [IOS_CLIENT_ID, WEB_CLIENT_ID].every(
    id => id.endsWith('.apps.googleusercontent.com') && /^\d{6,}-/.test(id),
  );
}
